# Generated by Django 5.2.4 on 2025-11-19 00:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedSignupDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllowSignupEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Organ System',
                'verbose_name_plural': '__add_organ_system',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Uploading staff',
                'verbose_name_plural': '__add_uploading_staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinalModel',
            fields=[
                ('model_type', models.CharField(choices=[('E', 'Exam'), ('U', 'Unknown'), ('G', 'Gross')], max_length=15)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('organ_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='api.organsystem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='api.staffuploader')),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Add question set',
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinical_information', models.TextField()),
                ('question', models.CharField(max_length=250)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.finalmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SlideModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accession_no', models.CharField(help_text='APL Accession Number', max_length=20)),
                ('slide_no', models.CharField(max_length=10)),
                ('stem', models.SlugField(blank=True, editable=False, help_text='Auto generated identifier from acccession number', max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_path', models.CharField(blank=True, default='', max_length=255)),
                ('dzi_xml_path', models.CharField(blank=True, default='', max_length=255)),
                ('dzi_tiles_path', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.questionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
