# Generated by Django 5.2.4 on 2025-11-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidemodel',
            name='svs_file',
            field=models.FilePathField(match='.*\\.svs$', max_length=500, path='/absolute/path/on/dev/or/server', recursive=True),
        ),
    ]
