# Generated by Django 5.2.4 on 2025-11-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidemodel',
            name='accession_no',
            field=models.CharField(blank=True, help_text='APL Accession Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this slide/file set is.'),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='slide_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='stem',
            field=models.SlugField(blank=True, editable=False, help_text='Internal key matching converted files (thumbnails/DZI).', max_length=255),
        ),
    ]
