# Generated by Django 5.2.4 on 2025-11-19 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_slidemodel_accession_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidemodel',
            name='accession_no',
            field=models.CharField(help_text='APL accession number', max_length=20),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.questionmodel'),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='slide_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='stem',
            field=models.SlugField(blank=True, editable=False, help_text='Auto-generated identifier from accession + slide', max_length=255),
        ),
    ]
